// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAry6AcUgu82-s515SN-zXJFk_QlVtu1oo',
    appId: '1:997175651224:web:fd51948f9e85fa4d1059ed',
    messagingSenderId: '997175651224',
    projectId: 'alert-crypto-66622',
    authDomain: 'alert-crypto-66622.firebaseapp.com',
    storageBucket: 'alert-crypto-66622.appspot.com',
    measurementId: 'G-WPMNL83PSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSokcIbdNvXQPATFCsMljBN4by6KBp0mM',
    appId: '1:997175651224:android:34abf49efa3da0591059ed',
    messagingSenderId: '997175651224',
    projectId: 'alert-crypto-66622',
    storageBucket: 'alert-crypto-66622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYQ_qOUwRFj0hEi4zkjZXWeCspU-Imc-E',
    appId: '1:997175651224:ios:76e6f262eb43d1be1059ed',
    messagingSenderId: '997175651224',
    projectId: 'alert-crypto-66622',
    storageBucket: 'alert-crypto-66622.appspot.com',
    iosClientId: '997175651224-it4hkf704pgq8q2mfeiovc95u30el7vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.priceAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYQ_qOUwRFj0hEi4zkjZXWeCspU-Imc-E',
    appId: '1:997175651224:ios:76e6f262eb43d1be1059ed',
    messagingSenderId: '997175651224',
    projectId: 'alert-crypto-66622',
    storageBucket: 'alert-crypto-66622.appspot.com',
    iosClientId: '997175651224-it4hkf704pgq8q2mfeiovc95u30el7vr.apps.googleusercontent.com',
    iosBundleId: 'com.example.priceAlert',
  );
}
